#!/bin/bash

#function smerp
#{
	#echo "derp"
#}


CRAWLER_OUT_PATH="./downloads"
FORMAT_OUT_PATH="./formatOut"
EXTRACT_SPRITE_OUT_PATH="./extractSpriteOut"
EXTRACT_BINDINGS_OUT_PATH="./"
TIBIA_SPR_PATH=""
TIBIA_DAT_PATH=""
IDENTIFY_EXECUTABLE_PATH="./bin/Release/spriteIdentifier"
IDENTIFY_OUT_PATH="./identifyOut"

function doDownload
{
	echo "Downloading sprites from tibia.wikia.com to '$CRAWLER_OUT_PATH'."
	python ../crawler/gief-them-gifs-from-generic-categories.py	
}

function doFormat
{
	echo "Formatting sprites from '$CRAWLER_OUT_PATH' to '$FORMAT_OUT_PATH'."
	/bin/bash formatSprites "$CRAWLER_OUT_PATH" "$FORMAT_OUT_PATH"
}

function extractSpritesMenu
{
	echo "Extracting sprites from Tibia.spr."
	echo "Enter the path to Tibia.spr: "
	read TIBIA_SPR_PATH
	
	if [ ! -f "$TIBIA_SPR_PATH" ]
	then
		echo "Invalid file path. Try again: "
		extractSpritesMenu
	fi
}

function doExtractSprites
{
	echo "Extracting sprites from '$TIBIA_SPR_PATH' to '$EXTRACT_SPRITE_OUT_PATH'."
	python3 extractSprites.py -i "$TIBIA_SPR_PATH" -o "$EXTRACT_SPRITE_OUT_PATH"
}

function extractBindingsMenu
{
	echo "Extracting sprite-object-bindings."
	echo "Enter the path to Tibia.dat"
	read TIBIA_DAT_PATH
	
	if [ ! -f "$TIBIA_DAT_PATH" ]
	then
		echo "Invalid file path. Try again: "
		extractBindingsMenu
	fi
}

function doExtractBindings
{
	echo "Extracting sprite-object-bindings from '$TIBIA_DAT_PATH' to '$EXTRACT_BINDINGS_OUT_PATH'"
	python3 extractData.py -i "$TIBIA_DAT_PATH" -s "$EXTRACT_SPRITE_OUT_PATH" -o "$EXTRACT_BINDINGS_OUT_PATH"
}

function buildIdentifierMenu
{
	echo "Cannot find the spriteIdentifier executable at '$IDENTIFY_EXECUTABLE_PATH'."
	echo "Maybe you haven't built it? Do you want me to build it for you? (y): "
	read yn
	if [[ "$yn" == "y" ]]
	then
		echo "Building executable..."
		make
	else
		echo "Aborting."
		exit
	fi
}

CRAWLER_OUT_PATH="./downloads"
FORMAT_OUT_PATH="./formatOut"
EXTRACT_SPRITE_OUT_PATH="./extractSpriteOut"
EXTRACT_BINDINGS_OUT_PATH="./spriteObjectBindings.txt"
TIBIA_SPR_PATH=""
TIBIA_DAT_PATH=""
IDENTIFY_EXECUTABLE_PATH="./bin/Release/spriteIdentifier"
IDENTIFY_OUT_PATH="./identifyOut"

function doIdentifySprites
{
	echo "Identifying sprites from tibia.wikia.com at '$CRAWLER_OUT_PATH' with "
	echo "sprites from Tibia.spr at '$EXTRACT_SPRITE_OUT_PATH'."
	echo "Using bindings file at '$EXTRACT_BINDINGS_OUT_PATH'."
	echo "Outputting to '$IDENTIFY_OUT_PATH'."
	"$IDENTIFY_EXECUTABLE_PATH" "$EXTRACT_SPRITE_OUT_PATH" "$EXTRACT_BINDINGS_OUT_PATH" "$FORMAT_OUT_PATH" "$IDENTIFY_OUT_PATH"
}

function optionsMenu
{
	echo "1. Download sprites from tibia.wikia.com."
	echo "2. Format sprites downloaded from tibia.wikia.com."
	echo "3. Extract sprites from Tibia.spr."
	echo "4. Extract sprite-object-bindings from Tibia.dat."
	echo "5. Identify sprites extracted from Tibia.spr with sprites from tibia.wikia.com."
	echo "6. 1-5."
	echo "7. 2-5."

	echo "What do you want to do? Enter a number from the list: "
	read option
	
	case "$option" in
		"1")
			doDownload
			;;
		"2")
			doFormat
			;;
		"3")
			extractSpritesMenu
			doExtractSprites
			;;
		"4")
			extractBindingsMenu
			doExtractBindings
			;;
		"5")
			if [ ! -f "$IDENTIFY_EXECUTABLE_PATH" ]
			then
				buildIdentifierMenu
			fi
			
			doIdentifySprites
			;;
		"6")
			
			;;
		"7")
		
			;;
		*)
			optionsMenu
			;;
	esac
	
	optionsMenu
}

optionsMenu
